In [1]:
# Dataset is glove 6B 50T
# udemy nlp with python

### install dependencies
only do this once

In [2]:
#! python3 -m venv venv
#! source venv/bin/activate
#! pip3 install -r requirements.txt
#! pip install ipykernel
#! python -m ipykernel install --user
#! pip freeze

### imports

In [1]:
from builtins import range
import numpy as np
import pandas as pd

In [2]:
from embedding_utilities import euclidean_dist, cosine_dist
from embedding import Embedding

In [10]:
glove_path_en = '../large-files/glove6B/glove.6B.50d.txt'
glove_path_de = '../large-files/GloVe_vectors_de.txt'

### the cosine distance does not change when doubeling
cosine distance only takes into account angle (the smaller the higher the similarity.)

euclidian looks at absolute length

In [4]:
a = pd.Series([1,1])
b = pd.Series([1,2])
print(f'euclidian distance {euclidean_dist(a,b)}')
print(f'cosine distance {cosine_dist(a,b)}')

euclidian distance 1.0
cosine distance 0.05131670194948623


In [5]:
a_double = a*2
b_double = b*2
print(f'euclidian distance {euclidean_dist(a_double,b_double)}')
print(f'cosine distance {cosine_dist(a_double,b_double)}')

euclidian distance 2.0
cosine distance 0.05131670194948623


In [6]:
dist, metric = cosine_dist, 'cosine'
#alternative: dist, metric = dist1, 'euclidean'

### load pretrained word vectors
source: https://www.kaggle.com/anindya2906/glove6b

In [8]:
glove_embedding_en = Embedding(language='en', path=glove_path_en)
print(glove_embedding_en.embedding.shape)
glove_embedding_en.embedding.head(1)

loading word embeddings word to vec from path ../large-files/glove6B/glove.6B.50d.txt
line number 200000
soroca 0.049805 -0.92157 -0.78814 0.40001 0.73747 0.23841 1.0884 0.74811 0.35275 -0.092519 0.068657 -1.5069 0.71963 -0.62382 0.42556 -0.12594 0.12767 0.48246 0.747 0.95415 -0.61376 -0.41512 -0.04666 0.91667 -0.70671 0.71371 -0.09069 0.63914 -0.22234 -0.51031 -1.009 -0.93208 0.53891 -0.32442 0.060975 0.12915 -0.17024 0.29168 0.14596 0.18409 -0.16361 0.21103 -0.092295 -0.49671 -1.3887 0.29717 0.070581 -0.19783 -0.62638 0.25806

line number 400000
sandberger 0.072617 -0.51393 0.4728 -0.52202 -0.35534 0.34629 0.23211 0.23096 0.26694 0.41028 0.28031 0.14107 -0.30212 -0.21095 -0.10875 -0.33659 -0.46313 -0.40999 0.32764 0.47401 -0.43449 0.19959 -0.55808 -0.34077 0.078477 0.62823 0.17161 -0.34454 -0.2066 0.1323 -1.8076 -0.38851 0.37654 -0.50422 -0.012446 0.046182 0.70028 -0.010573 -0.83629 -0.24698 0.6888 -0.17986 -0.066569 -0.48044 -0.55946 -0.27594 0.056072 -0.18907 -0.59021 0.55559

tota

0        1        2       3        4         5        6        7   \
the  0.418  0.24968 -0.41242  0.1217  0.34527 -0.044457 -0.49688 -0.17862   

          8       9   ...       40       41       42        43       44  \
the -0.00066 -0.6566  ... -0.29871 -0.15749 -0.34758 -0.045637 -0.44251   

          45        46       47       48       49  
the  0.18785  0.002785 -0.18411 -0.11514 -0.78581  

[1 rows x 50 columns]

In [11]:
glove_embedding_de = Embedding(language='de', path=glove_path_de)
print(glove_embedding_de.embedding.shape)
glove_embedding_de.embedding.head(1)

loading word embeddings word to vec from path ../large-files/GloVe_vectors_de.txt
line number 200000
fearn 0.358711 0.228275 -0.462231 0.750768 0.185820 -0.783655 0.169267 0.813484 -0.308528 -0.267102 0.004849 -0.445587 0.067366 -0.060609 0.473951 0.120780 0.104308 0.009122 0.625654 -0.070514 0.259300 -0.784249 0.257153 0.006716 0.266172 0.519422 0.167962 0.053425 0.274593 -0.119799 0.345878 0.297199 -0.020292 0.471211 0.053282 -0.240481 0.141987 -0.039940 -0.116287 -0.094897 0.162752 0.043128 -0.239818 -0.161584 -0.250876 -0.605242 -0.303547 -0.091675 -0.303955 0.069831 1.020646 0.458501 -0.267974 -0.489772 -0.427543 -0.136270 0.213337 -0.040638 0.374368 0.001954 0.557959 0.152819 0.075516 0.054921 -0.165086 -0.625599 -0.085677 -0.043549 -0.238558 -0.191032 -0.656133 0.008720 0.421783 0.053457 0.730938 0.201390 -0.724822 0.073857 0.337435 -0.007155 0.285931 -0.383834 -0.195941 0.054973 -0.299280 -0.307241 0.330514 -0.099103 0.457517 -0.036622 -0.014664 0.069571 -0.030285 0.121525 0.47

0        1         2         3        4         5         6    \
der -0.28062  0.74426  0.257364 -0.070038 -0.07914 -0.134922  0.418708   

          7         8         9    ...       290      291       292       293  \
der  0.373415  0.074699 -0.791163  ... -0.138816 -0.45058 -0.136059 -0.005833   

          294      295       296     297       298       299  
der -0.425212 -0.04491  0.159463 -0.4145  0.046645  0.069972  

[1 rows x 300 columns]

In [13]:
print(glove_embedding_en.word2vec['tree'][:10])
print(glove_embedding_de.word2vec['baum'][:10])

[ 0.62231   1.1986   -0.014116  0.20125   0.69419   0.12068  -0.90399
 -1.4023    0.43357  -0.48537 ]
[-0.400554  0.139754 -0.357781  0.45136  -0.178334  0.052695 -0.75287
 -0.285123  0.048494  0.015669]


In [14]:
print(glove_embedding_en.index_to_word[1])
print(glove_embedding_de.index_to_word[1])

,
und


In [15]:
print(glove_embedding_en.embedding.shape)
print(glove_embedding_de.embedding.shape)

(400000, 50)
(1309281, 300)


# Best of

In [17]:
glove_embedding_en.find_analogies('fun', 'man', 'woman')
glove_embedding_de.find_analogies('freude', 'mann', 'frau')

fun - man = kids - woman
freude - mann = mutter - frau


'mutter'

In [18]:
glove_embedding_en.find_analogies('love', 'woman', 'man')
glove_embedding_de.find_analogies('liebe', 'frau', 'mann')

love - woman = me - man
liebe - frau = mein - mann


'mein'

In [19]:
glove_embedding_en.find_analogies('motivation', 'man', 'woman')
glove_embedding_de.find_analogies('motivation', 'mann', 'frau')

motivation - man = satisfaction - woman
motivation - mann = beeinflussen - frau


'beeinflussen'

In [20]:
glove_embedding_en.find_analogies('motivation', 'woman', 'man')
glove_embedding_de.find_analogies('motivation', 'frau', 'mann')

motivation - woman = tremendous - man
motivation - frau = stärke - mann


'stärke'

In [21]:
glove_embedding_en.find_analogies('respect', 'man', 'woman')
glove_embedding_de.find_analogies('respekt', 'mann', 'frau')

respect - man = recognizing - woman
respekt - mann = wertschätzung - frau


'wertschätzung'

In [23]:
glove_embedding_en.find_analogies('success', 'man', 'woman')
glove_embedding_de.find_analogies('erfolg', 'mann', 'woman')

success - man = recognition - woman
erfolg - mann = hit - woman


'hit'

In [24]:
glove_embedding_en.find_analogies('love', 'man', 'woman')
glove_embedding_de.find_analogies('liebe', 'mann', 'frau')

love - man = mother - woman
liebe - mann = mutter - frau


'mutter'

In [25]:
glove_embedding_en.find_analogies('great', 'man', 'woman')
glove_embedding_de.find_analogies('großartig', 'mann', 'frau')

great - man = life - woman
großartig - mann = langweilig - frau


'langweilig'

In [31]:
glove_embedding_en.find_analogies('kids', 'woman', 'man')
glove_embedding_de.find_analogies('kinder', 'frau', 'mann')

kids - woman = guys - man
kinder - frau = kindern - mann


'kindern'

In [30]:
glove_embedding_en.find_analogies('friends', 'woman', 'man')
glove_embedding_de.find_analogies('freund', 'frau', 'mann')

friends - woman = wanted - man
freund - frau = freunde - mann


'freunde'

In [33]:
glove_embedding_en.find_analogies('friends', 'men', 'women')
glove_embedding_de.find_analogies('freunde', 'männer', 'frauen')

friends - men = parents - women
freunde - männer = ihrer - frauen


'ihrer'

In [34]:
glove_embedding_en.find_analogies('safety', 'woman', 'man')
glove_embedding_de.find_analogies('sicherheit', 'frau', 'mann')

safety - woman = tackle - man
sicherheit - frau = ausrüstung - mann


'ausrüstung'

In [36]:
glove_embedding_en.find_analogies('orgasm', 'woman', 'men')
glove_embedding_de.find_analogies('orgasmus', 'frauen', 'männer')

orgasm - woman = orgasms - men
orgasmus - frauen = hengzt - männer


'hengzt'

In [37]:
# klappt einfach
glove_embedding_en.find_analogies('man', 'woman', 'she')
glove_embedding_en.find_analogies('man', 'woman', 'aunt')
glove_embedding_en.find_analogies('man', 'woman', 'sister')
glove_embedding_en.find_analogies('man', 'woman', 'actress')
glove_embedding_en.find_analogies('man', 'woman', 'mother')

man - woman = he - she
man - woman = uncle - aunt
man - woman = brother - sister
man - woman = actor - actress
man - woman = father - mother


'father'

In [38]:
# klappt einfach
glove_embedding_de.find_analogies('mann', 'frau', 'sie')
glove_embedding_de.find_analogies('mann', 'frau', 'tante')
glove_embedding_de.find_analogies('mann', 'frau', 'schwester')
glove_embedding_de.find_analogies('mann', 'frau', 'schauspielerin')
glove_embedding_de.find_analogies('mann', 'frau', 'mutter')

mann - frau = aber - sie
mann - frau = freund - tante
mann - frau = bruder - schwester
mann - frau = schauspieler - schauspielerin
mann - frau = vater - mutter


'vater'

In [40]:
#klappt einfach
glove_embedding_en.find_analogies('france', 'paris', 'london')
glove_embedding_en.find_analogies('france', 'paris', 'rome')
glove_embedding_en.find_analogies('paris', 'france', 'italy')
glove_embedding_en.find_analogies('miami', 'florida', 'texas')

france - paris = britain - london
france - paris = italy - rome
paris - france = rome - italy
miami - florida = houston - texas


'houston'

In [39]:
glove_embedding_de.find_analogies('frankreich', 'paris', 'london')
glove_embedding_de.find_analogies('frankreich', 'paris', 'rom')
glove_embedding_de.find_analogies('paris', 'frankreich', 'italien')
glove_embedding_de.find_analogies('miami', 'florida', 'texas')

frankreich - paris = großbritannien - london
frankreich - paris = italien - rom
paris - frankreich = rom - italien
miami - florida = houston - texas


'houston'

In [41]:
#klappt einfach
glove_embedding_en.find_analogies('november', 'december', 'march')
glove_embedding_de.find_analogies('november', 'dezember', 'märz')

november - december = april - march
november - dezember = oktober - märz


'oktober'

In [42]:
#klappt einfach
glove_embedding_en.find_analogies('einstein', 'scientist', 'painter')
glove_embedding_de.find_analogies('einstein', 'wissenschaftler', 'maler')

einstein - scientist = matisse - painter
einstein - wissenschaftler = grafiker - maler


'grafiker'

In [44]:
# fun
glove_embedding_en.find_analogies('rice', 'china', 'germany')
glove_embedding_de.find_analogies('reis', 'china', 'deutschland')

rice - china = bacon - germany
reis - china = kartoffeln - deutschland


'kartoffeln'

In [45]:
glove_embedding_en.find_analogies('beer', 'germany', 'usa')
glove_embedding_de.find_analogies('bier', 'deutschland', 'usa')

beer - germany = pepsi - usa
bier - deutschland = gebraut - usa


'gebraut'

In [46]:
glove_embedding_en.find_analogies('freedom', 'usa', 'germany')
glove_embedding_de.find_analogies('freiheit', 'usa', 'deutschland')

freedom - usa = germans - germany
freiheit - usa = demokratie - deutschland


'demokratie'

In [48]:
glove_embedding_en.find_analogies('building', 'builder', 'politician')
glove_embedding_en.find_analogies('book', 'writer', 'politician')
glove_embedding_de.find_analogies('baustelle', 'bauarbeiter', 'politiker')
glove_embedding_de.find_analogies('buch', 'schriftsteller', 'politiker')

building - builder = elected - politician
book - writer = party - politician
baustelle - bauarbeiter = jurist - politiker
buch - schriftsteller = mitglied - politiker


'mitglied'

In [49]:
glove_embedding_en.find_analogies('code', 'hacker', 'politician')
glove_embedding_de.find_analogies('code', 'hacker', 'politiker')

code - hacker = elected - politician
code - hacker = jurist - politiker


'jurist'

# nearest neighbors

In [50]:
glove_embedding_en.nearest_neighbors('france')

neighbors of: france
	french
	belgium
	paris
	spain
	netherlands


array([ 348, 2975, 1035, 1029, 2238])

In [52]:
glove_embedding_de.nearest_neighbors('frankreich')

neighbors of: frankreich
	italien
	französischen
	großbritannien
	spanien
	belgien


array([ 480,  457, 1095,  804, 1423])

In [53]:
glove_embedding_en.nearest_neighbors('einstein')
glove_embedding_de.nearest_neighbors('einstein')

neighbors of: einstein
	relativity
	bohr
	physics
	heisenberg
	freud
neighbors of: einstein
	einsteins
	physik
	heisenberg
	poincaré
	mileva


array([ 48160,   2371,  28521,  31601, 250921])

In [54]:
glove_embedding_en.nearest_neighbors('trump')
glove_embedding_de.nearest_neighbors('trump')

neighbors of: trump
	casino
	nows
	casinos
	hilton
	mogul
neighbors of: trump
	trumps
	obama
	barack
	bush
	clinton


array([43972, 13007, 19208,  7553,  9118])

In [55]:
glove_embedding_en.nearest_neighbors('merkel')
glove_embedding_de.nearest_neighbors('merkel')

neighbors of: merkel
	schroeder
	sarkozy
	kohl
	steinmeier
	chirac
neighbors of: merkel
	bundeskanzlerin
	bundeskanzler
	angela
	schröder
	kanzlerin


array([29678, 10167,  5671,  4245, 81235])

In [56]:
glove_embedding_en.nearest_neighbors('procrastination')
glove_embedding_de.nearest_neighbors('prokrastination')

neighbors of: procrastination
	remedying
	rationalizing
	rationalization
	aggravation
	misjudgment
neighbors of: prokrastination
	huraa
	trichodynie
	browserweichen
	rangierfeld
	terekura


array([1264153, 1162555, 1177566, 1047241, 1161246])

In [57]:
glove_embedding_en.nearest_neighbors('religion')
glove_embedding_de.nearest_neighbors('religion')

neighbors of: religion
	beliefs
	religious
	religions
	christianity
	belief
neighbors of: religion
	christentum
	religionen
	glauben
	islam
	glaube


array([4607, 6201, 2933, 3476, 7079])

In [ ]:
nearest_neighbors('woman',index_to_word, word2vec)
nearest_neighbors('man',index_to_word, word2vec)
nearest_neighbors('nephew',index_to_word, word2vec)

In [ ]:
nearest_neighbors('february',index_to_word, word2vec)
nearest_neighbors('success',index_to_word, word2vec)
nearest_neighbors('money',index_to_word, word2vec)
nearest_neighbors('love',index_to_word, word2vec)

In [ ]:
nearest_neighbors('procrastination', index_to_word, word2vec)